apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline
  namespace: keklund-demo
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/keklundrh/kee-demo-pipeline.git'
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: demo-pipeline
  workspaces:
    - name: demo-pipeline

